# Generated by Django 2.2.4 on 2022-02-22 23:27

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='Nickname')),
                ('about', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(choices=[('N/A', 'Prefer Not to Choose'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=25, verbose_name='Gender(Optional)')),
                ('picture', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.user_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
